// Copyright (c) Aptos Foundation
// Licensed pursuant to the Innovation-Enabling Source Code License, available at https://github.com/aptos-labs/aptos-core/blob/main/LICENSE

//! Move package testing and coverage tools.

use super::super::{package_data::PackageData, session::FlowSession, McpArgs};
use aptos_framework::extended_checks;
use aptos_gas_schedule::{MiscGasParameters, NativeGasParameters, LATEST_GAS_FEATURE_VERSION};
use aptos_types::on_chain_config::{
    aptos_test_feature_flags_genesis, Features, TimedFeaturesBuilder,
};
use aptos_vm::natives;
use move_coverage::{coverage_map::CoverageMap, source_coverage::SourceCoverageBuilder};
use move_model::model::GlobalEnv;
use move_package::{BuildConfig, CompilerConfig};
use move_unit_test::{
    package_test::{run_move_unit_tests, UnitTestResult},
    test_validation, UnitTestingConfig,
};
use move_vm_runtime::native_functions::NativeFunctionTable;
use rmcp::{
    handler::server::wrapper::Parameters,
    model::{CallToolResult, Content},
    schemars, tool, tool_router,
};
use move_command_line_common::files::MOVE_COVERAGE_MAP_EXTENSION;
use regex::Regex;
use std::{
    collections::{hash_map::DefaultHasher, BTreeMap, BTreeSet},
    hash::{Hash, Hasher},
    path::Path,
    sync::Once,
};

/// Gas limit for unit test execution. Prevents infinite loops from hanging tests.
const TEST_GAS_LIMIT: u64 = 100_000;

/// Strip non-deterministic timing values from test output.
fn strip_timing(s: &str) -> String {
    let re = Regex::new(r"│\s+\d+\.\d+\s+│").expect("valid regex");
    re.replace_all(s, "│").to_string()
}

/// Path to the baseline coverage map file in system temp directory.
/// Uses a hash of the canonicalized package path to avoid collisions.
fn baseline_coverage_map_path(pkg_path: &Path) -> std::path::PathBuf {
    // Canonicalize to ensure ./pkg and /abs/pkg hash the same
    let canonical = pkg_path
        .canonicalize()
        .unwrap_or_else(|_| pkg_path.to_path_buf());

    let mut hasher = DefaultHasher::new();
    canonical.hash(&mut hasher);
    let hash = hasher.finish();

    std::env::temp_dir()
        .join("move_flow")
        .join(format!("baseline_coverage_{:x}.mvcov", hash))
}

/// Path to the coverage map file generated by the test runner.
fn coverage_map_path(pkg_path: &Path) -> std::path::PathBuf {
    pkg_path
        .join(".coverage_map")
        .with_extension(MOVE_COVERAGE_MAP_EXTENSION)
}

/// Initialize global test configuration (validation hooks, native function mode).
/// Uses `Once` to ensure thread-safe, single initialization across concurrent calls.
static TEST_INIT: Once = Once::new();

/// Get Aptos native functions for unit testing.
fn aptos_test_natives() -> NativeFunctionTable {
    TEST_INIT.call_once(|| {
        natives::configure_for_unit_test();
        test_validation::set_validation_hook(Box::new(|env: &GlobalEnv| {
            extended_checks::run_extended_checks(env);
        }));
    });

    natives::aptos_natives(
        LATEST_GAS_FEATURE_VERSION,
        NativeGasParameters::zeros(),
        MiscGasParameters::zeros(),
        TimedFeaturesBuilder::enable_all().build(),
        Features::default(),
    )
}

/// Create a build config suitable for testing, using MCP args.
fn make_test_build_config(pkg_path: &Path, args: &McpArgs) -> BuildConfig {
    let compiler_config = CompilerConfig {
        known_attributes: extended_checks::get_all_attribute_names().clone(),
        bytecode_version: args.bytecode_version,
        language_version: args.language_version,
        experiments: args.experiments.clone(),
        ..Default::default()
    };

    let additional_named_addresses = args
        .named_addresses
        .iter()
        .map(|(name, addr)| (name.clone(), addr.into_inner()))
        .collect();

    BuildConfig {
        test_mode: true,
        dev_mode: args.dev_mode,
        install_dir: Some(pkg_path.join("build")),
        compiler_config,
        full_model_generation: true,
        additional_named_addresses,
        ..Default::default()
    }
}

/// Run Move unit tests for a package with coverage enabled.
/// Returns (success, output) where output is the test output string.
fn run_tests(pkg_path: &Path, args: &McpArgs) -> anyhow::Result<(bool, String)> {
    log::info!("running tests for `{}`", pkg_path.display());

    let build_config = make_test_build_config(pkg_path, args);
    let unit_test_config = UnitTestingConfig {
        report_statistics: true,
        ..Default::default()
    };

    let mut output = Vec::new();
    let result = run_move_unit_tests(
        pkg_path,
        build_config,
        unit_test_config,
        aptos_test_natives(),
        aptos_test_feature_flags_genesis(),
        Some(TEST_GAS_LIMIT),
        None,  // cost_table: use default
        true,  // compute_coverage: needed for coverage tracking
        &mut output,
        true,  // enable_enum_types
    );

    let output_str = strip_timing(&String::from_utf8_lossy(&output));
    match result {
        Ok(UnitTestResult::Success) => {
            log::info!("tests passed");
            Ok((true, output_str))
        },
        Ok(UnitTestResult::Failure) => {
            log::info!("tests failed");
            Ok((false, output_str))
        },
        Err(e) => {
            log::error!("test execution error: {}", e);
            Err(anyhow::anyhow!("test execution failed: {}", e))
        },
    }
}

/// Save the current coverage map as baseline by copying it to
/// a temp directory with a filename hashed from the package canonical path.
/// If no coverage map exists (no tests), creates an empty baseline.
fn save_baseline_coverage_map(pkg_path: &Path) -> anyhow::Result<()> {
    let src = coverage_map_path(pkg_path);
    let dst = baseline_coverage_map_path(pkg_path);

    if let Some(parent) = dst.parent() {
        std::fs::create_dir_all(parent)?;
    }

    if src.exists() {
        std::fs::copy(&src, &dst)?;
        log::info!("Saved baseline coverage to {}", dst.display());
    } else {
        // No tests exist yet - create empty baseline
        let empty = CoverageMap::default();
        move_coverage::coverage_map::output_map_to_file(&dst, &empty)?;
        log::info!("Created empty baseline coverage at {}", dst.display());
    }
    Ok(())
}

// ========== MCP Tool types ==========

/// Parameters for `move_package_test` tool.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
struct MovePackageTestParams {
    /// Path to the Move package directory.
    package_path: String,
    /// If true, save current coverage as baseline for future comparisons.
    /// Use this in the first test run before generating new tests.
    #[serde(default)]
    establish_baseline: bool,
}

/// Response for `move_package_test` tool
#[derive(Debug, serde::Serialize)]
struct TestResponse {
    /// Whether all tests passed.
    success: bool,
    /// Whether baseline was established (only in baseline mode).
    #[serde(skip_serializing_if = "Option::is_none")]
    baseline_established: Option<bool>,
    /// Lines that became covered since baseline (only in normal mode).
    /// Maps source file path to list of newly covered line numbers.
    #[serde(skip_serializing_if = "Option::is_none")]
    newly_covered: Option<BTreeMap<String, Vec<u32>>>,
    /// Test output (only on failure).
    #[serde(skip_serializing_if = "Option::is_none")]
    output: Option<String>,
}

/// Parameters for `move_package_coverage` tool.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
struct MovePackageCoverageParams {
    /// Path to the Move package directory.
    package_path: String,
}

/// Response for `move_package_coverage` tool
#[derive(Debug, serde::Serialize)]
struct CoverageResponse {
    /// Uncovered lines per source file.
    /// Maps source file path to list of uncovered line numbers.
    uncovered: BTreeMap<String, Vec<u32>>,
}

// ========== Internal helpers ==========

/// Convert uncovered locations from a SourceCoverageBuilder to line numbers.
fn uncovered_lines(builder: &SourceCoverageBuilder, env: &GlobalEnv) -> BTreeSet<u32> {
    builder
        .uncovered_locations
        .iter()
        .filter_map(|loc| env.get_location(&env.to_loc(loc)))
        .map(|location| location.line.0 + 1)
        .collect()
}

/// Compute uncovered lines from the current coverage map using SourceCoverageBuilder.
/// Returns a map from source file path to list of uncovered line numbers.
fn compute_uncovered(
    pkg_path: &Path,
    pkg_data: &mut PackageData,
) -> anyhow::Result<Option<BTreeMap<String, Vec<u32>>>> {
    let cov_map_path = coverage_map_path(pkg_path);
    if !cov_map_path.exists() {
        return Ok(None);
    }

    if !pkg_data.has_bytecode() {
        pkg_data.rebuild_with_bytecode()?;
    }
    let env = pkg_data.env();
    let cov_map = CoverageMap::from_binary_file(&cov_map_path)?;

    let mut result: BTreeMap<String, BTreeSet<u32>> = BTreeMap::new();

    for module in env.get_modules() {
        if !module.is_target() {
            continue;
        }
        let (compiled_module, source_map) =
            match (module.get_verified_module(), module.get_source_map()) {
                (Some(cm), Some(sm)) => (cm, sm),
                _ => continue,
            };
        let source_path = module.get_source_path().to_string_lossy().to_string();
        let builder =
            SourceCoverageBuilder::new(&cov_map, source_map, vec![(compiled_module, source_map)]);
        let lines = uncovered_lines(&builder, env);

        if !lines.is_empty() {
            result.entry(source_path).or_default().extend(lines);
        }
    }

    Ok(Some(
        result
            .into_iter()
            .map(|(path, lines)| (path, lines.into_iter().collect()))
            .collect(),
    ))
}

/// Compare baseline and new coverage to find newly covered lines.
/// Returns lines that were uncovered in baseline but are now covered.
fn compute_newly_covered(
    pkg_path: &Path,
    pkg_data: &mut PackageData,
) -> anyhow::Result<Option<BTreeMap<String, Vec<u32>>>> {
    let cov_map_path = coverage_map_path(pkg_path);
    if !cov_map_path.exists() {
        return Ok(None);
    }

    if !pkg_data.has_bytecode() {
        pkg_data.rebuild_with_bytecode()?;
    }
    let env = pkg_data.env();

    let current_cov = CoverageMap::from_binary_file(&cov_map_path)?;
    let baseline_path = baseline_coverage_map_path(pkg_path);
    let baseline_cov = if baseline_path.exists() {
        CoverageMap::from_binary_file(&baseline_path)?
    } else {
        CoverageMap::default()
    };

    let mut result: BTreeMap<String, BTreeSet<u32>> = BTreeMap::new();

    for module in env.get_modules() {
        if !module.is_target() {
            continue;
        }
        let (compiled_module, source_map) =
            match (module.get_verified_module(), module.get_source_map()) {
                (Some(cm), Some(sm)) => (cm, sm),
                _ => continue,
            };
        let source_path = module.get_source_path().to_string_lossy().to_string();
        let module_info = vec![(compiled_module, source_map)];

        let baseline_builder =
            SourceCoverageBuilder::new(&baseline_cov, source_map, module_info.clone());
        let current_builder =
            SourceCoverageBuilder::new(&current_cov, source_map, module_info);

        // Newly covered = was uncovered before, but is covered now
        let uncovered_before = uncovered_lines(&baseline_builder, env);
        let uncovered_now = uncovered_lines(&current_builder, env);
        let newly_covered: BTreeSet<u32> =
            uncovered_before.difference(&uncovered_now).copied().collect();

        if !newly_covered.is_empty() {
            result.entry(source_path).or_default().extend(newly_covered);
        }
    }

    Ok(Some(
        result
            .into_iter()
            .map(|(path, lines)| (path, lines.into_iter().collect()))
            .collect(),
    ))
}

// ========== MCP Tools ==========

/// Convert a TestResponse to a CallToolResult (success or error based on test outcome).
fn test_response_to_result(response: TestResponse) -> Result<CallToolResult, rmcp::ErrorData> {
    let json = serde_json::to_string_pretty(&response)
        .map_err(|e| rmcp::ErrorData::internal_error(format!("JSON serialization failed: {}", e), None))?;
    Ok(if response.success {
        CallToolResult::success(vec![Content::text(json)])
    } else {
        CallToolResult::error(vec![Content::text(json)])
    })
}

#[tool_router(router = package_test_router, vis = "pub(crate)")]
impl FlowSession {
    /// Run tests and optionally establish baseline or report newly covered lines.
    #[tool(
        description = "Run Move unit tests for a package. Set establish_baseline=true to save \
                          current coverage as baseline (use before generating new tests). Without \
                          establish_baseline, returns lines newly covered since baseline. If no \
                          baseline exists, all covered lines are reported as newly_covered."
    )]
    async fn move_package_test(
        &self,
        Parameters(params): Parameters<MovePackageTestParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        log::info!(
            "move_package_test: path=`{}` establish_baseline={}",
            params.package_path,
            params.establish_baseline
        );

        let pkg_path = std::path::PathBuf::from(&params.package_path);
        if !pkg_path.exists() {
            return Ok(CallToolResult::error(vec![Content::text(format!(
                "package path does not exist: {}",
                params.package_path
            ))]));
        }

        // Run tests (offload to blocking thread pool)
        let args = self.args().clone();
        let pkg_path_clone = pkg_path.clone();
        let (success, output) =
            match tokio::task::spawn_blocking(move || run_tests(&pkg_path_clone, &args))
                .await
                .map_err(|e| format!("test task panicked: {}", e))
                .and_then(|r| r.map_err(|e| e.to_string()))
            {
                Ok(result) => result,
                Err(e) => {
                    log::error!("move_package_test failed: {}", e);
                    return Ok(CallToolResult::error(vec![Content::text(e)]));
                },
            };

        // Baseline mode: save current coverage as reference point for future comparisons.
        // Only save on success to ensure baseline reflects a valid test run.
        if params.establish_baseline {
            if success {
                save_baseline_coverage_map(&pkg_path).map_err(|e| {
                    rmcp::ErrorData::internal_error(format!("Failed to save baseline: {}", e), None)
                })?;
            }
            log::info!(
                "move_package_test: tests {}, baseline {}",
                if success { "passed" } else { "failed" },
                if success { "saved" } else { "not saved" }
            );
            return test_response_to_result(TestResponse {
                success,
                baseline_established: Some(success),
                newly_covered: None,
                output: if success { None } else { Some(output) },
            });
        }

        // Normal mode: compare current coverage against baseline to find newly covered lines.
        // Skip coverage analysis on test failure (coverage map may be stale or incomplete).
        let newly_covered = if success {
            let package_data = self.resolve_package(&params.package_path).await.map_err(|e| {
                rmcp::ErrorData::internal_error(format!("Failed to resolve package: {}", e), None)
            })?;
            let mut guard = package_data.lock().map_err(|_| {
                rmcp::ErrorData::internal_error("package lock poisoned", None)
            })?;
            compute_newly_covered(&pkg_path, &mut guard).map_err(|e| {
                rmcp::ErrorData::internal_error(format!("Failed to compute coverage: {}", e), None)
            })?
        } else {
            None
        };

        let newly_covered_count: usize = newly_covered
            .as_ref()
            .map(|nc| nc.values().map(|lines| lines.len()).sum())
            .unwrap_or(0);
        log::info!(
            "move_package_test: tests {}, {} newly covered lines",
            if success { "passed" } else { "failed" },
            newly_covered_count
        );

        test_response_to_result(TestResponse {
            success,
            baseline_established: None,
            newly_covered,
            output: if success { None } else { Some(output) },
        })
    }

    #[tool(
        description = "Get uncovered source lines for a package. \
                          Uses existing coverage map if available, otherwise runs tests first. \
                          Use this to identify which code paths need test coverage."
    )]
    async fn move_package_coverage(
        &self,
        Parameters(params): Parameters<MovePackageCoverageParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        log::info!("move_package_coverage: path=`{}`", params.package_path);

        let pkg_path = std::path::PathBuf::from(&params.package_path);
        if !pkg_path.exists() {
            return Ok(CallToolResult::error(vec![Content::text(format!(
                "package path does not exist: {}",
                params.package_path
            ))]));
        }

        // Generate coverage map by running tests if none exists.
        if !coverage_map_path(&pkg_path).exists() {
            log::info!("move_package_coverage: no coverage map, running tests first");
            let args = self.args().clone();
            let pkg_path_clone = pkg_path.clone();
            let (success, output) =
                tokio::task::spawn_blocking(move || run_tests(&pkg_path_clone, &args))
                    .await
                    .map_err(|e| {
                        rmcp::ErrorData::internal_error(format!("test task panicked: {}", e), None)
                    })?
                    .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;
            if !success {
                return Ok(CallToolResult::error(vec![Content::text(format!(
                    "Tests failed. Fix tests before checking coverage.\n\n{}",
                    output
                ))]));
            }
        }

        // Compute uncovered lines from the coverage map.
        let package_data = self.resolve_package(&params.package_path).await.map_err(|e| {
            rmcp::ErrorData::internal_error(format!("Failed to resolve package: {}", e), None)
        })?;
        let mut guard = package_data.lock().map_err(|_| {
            rmcp::ErrorData::internal_error("package lock poisoned", None)
        })?;
        let uncovered = compute_uncovered(&pkg_path, &mut guard)
            .map_err(|e| {
                rmcp::ErrorData::internal_error(format!("Failed to compute coverage: {}", e), None)
            })?
            .unwrap_or_default();

        log::info!(
            "move_package_coverage: {} uncovered lines",
            uncovered.values().map(|l| l.len()).sum::<usize>()
        );

        let json = serde_json::to_string_pretty(&CoverageResponse { uncovered })
            .map_err(|e| rmcp::ErrorData::internal_error(format!("JSON serialization failed: {}", e), None))?;
        Ok(CallToolResult::success(vec![Content::text(json)]))
    }
}
